# yaml 설정파일
# 계층 구조로 설정
# 공통된 property 항목은 맨 앞줄부터 사용하고
# : 을 붙여준 후 이후의 속성들은 tab을 입력하여 들여쓰기 한 후 속성들을 설정
spring:
  devtools:
    restart.enabled: true
    remote.restart.enabled: true
  # 외부에서 접근하는 경로
  mvc:
    static-path-pattern: /static/**
  # 서버의 폴더 개방
  web:
    resources:
      static-locations: classpath:static/

# DBMS Setting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bootDB
    username: jinwoo8420
    password: '!Korea8080'

# ddl-auto의 update 속성
# 기존의 테이블이 있으면 Alter table을 실행하여 테이블 구조를 변경한다
  jpa:
    hibernate.ddl-auto: update
  properties:
    hibernate.show_sql: true
    hibernate.format_sql: true

  thymeleaf:
    prefix: classpath:html/
    suffix: .html
    mode: HTML5
    template-resolver-order: 0

# logback setup
logging:
  config: classpath:logback-local.xml
  level:
    com.callor.book: debug
    org.springframework: debug